version: "3"
services:
    guacd:
        image: guacamole/guacd:0.9.14
        networks:
            - safesurf
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASS}
        networks:
            - safesurf
    guacamole:
        image: guacamole/guacamole:0.9.14
        networks:
            - safesurf
        depends_on:
            - secretary
        environment:
            - GUACD_HOSTNAME=guacd
            - MYSQL_HOSTNAME=mysql
            - MYSQL_DATABASE=guac
            - MYSQL_USER=root
            - MYSQL_PASSWORD=${DB_PASS}
    nginx:
        image: nginx:1.16
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./web/static:/static
        ports:
            - ${SERVICE_PORT}:80
        networks:
            - safesurf
        depends_on:
            - guacamole
            - web
    secretary:
        build: ./secretary
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./secretary:/secretary
            - ./tools:/tools
            - ./guacamole:/guacamole
        environment:
            - MYSQL_PASSWORD=${DB_PASS}
        command: /secretary/run.sh
        depends_on:
            - guacd
            - mysql
        networks:
            - safesurf
    web:
        image: ubuntu
        command: vmstat 1
        depends_on:
            - mysql
        networks:
            - safesurf
networks:
    safesurf:
