version: "3"
services:
    guacd:
        image: guacamole/guacd:0.9.14
        networks:
            - safesurf
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASS}
        networks:
            - safesurf
    guacamole:
        image: guacamole/guacamole:0.9.14
        networks:
            - safesurf
        depends_on:
            - secretary
        environment:
            - GUACD_HOSTNAME=guacd
            - MYSQL_HOSTNAME=mysql
            - MYSQL_DATABASE=guac
            - MYSQL_USER=root
            - MYSQL_PASSWORD=${DB_PASS}
    nginx:
        image: nginx:1.16
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./web/webapp/static:/static
        ports:
            - ${SERVICE_PORT}:80
        networks:
            - safesurf
        depends_on:
            - guacamole
            - web
    secretary:
        build: ./secretary
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./secretary:/secretary
            - ./tools:/tools
            - ./guacamole:/guacamole
        environment:
            - MYSQL_PASSWORD=${DB_PASS}
        command: /secretary/run.sh
        depends_on:
            - guacd
            - mysql
        networks:
            - safesurf
    web:
        build: ./web
        command: /web/start.sh
        depends_on:
            - mysql
            - operator
        volumes:
            - ./web:/web
            - ./tools:/tools
            - ./setting.yaml:/setting.yaml
        environment:
            - MYSQL_PASSWORD=${DB_PASS}
        networks:
            - safesurf
    browser_dummy:
        build: ./browser
        image: safesurf-browser
        command: dummy
        networks:
            - safesurf
    operator:
        build: ./operator
        depends_on:
            - browser_dummy
            - mysql
        networks:
            - safesurf
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./setting.yaml:/setting.yaml
networks:
    safesurf:
